# Use our custom .gitpod.Dockerfile so that the correct Java versions are used
image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Start SpringPetClinic
    init: |
      ./mvnw clean install
      ./mvnw dependency:go-offline
      ./mvnw package 
      code --install-extension ContrastSecurity.contrastsecurity-2.0.0.vsix
    command: ./mvnw spring-boot:run

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: petclinic-dev
    description: Port 8080 for petclinic-dev running assess
    port: 8080
    onOpen: open-preview
  
  # - name: petclinic-prod
  #   description: Port 8081 for petclinic-prod running protect
  #   port: 8081
  #   onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

vscode:
  extensions: 
    - pivotal.vscode-spring-boot
    - pivotal.vscode-boot-dev-pack
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - redhat.java
    # - /workspace/demo-petclinic-taylor/ContrastSecurity.contrastsecurity-2.0.0.visx

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true