# Use our custom .gitpod.Dockerfile so that the correct Java versions are used
image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Start SpringPetClinic
    init: |
      ./mvnw clean install -U -DskipTests
      ./mvnw package -U -DskipTests
      code --install-extension ContrastSecurity.contrastsecurity-2.0.0.vsix
    command: |
      gp open README.md
      ./mvnw spring-boot:run

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: petclinic-dev
    description: Port 8080 for petclinic-dev running assess
    port: 8080
    onOpen: open-preview

vscode:
  extensions: 
    - pivotal.vscode-spring-boot
    - pivotal.vscode-boot-dev-pack
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - redhat.java
